### PR TITLE
Add comparison operators & ternary operator

### PR DESCRIPTION
**Pull request by shevchuk**

### CODE REVIEW

**Review by rm-hull — APPROVED** [review]
Looks good !

**Comment by shevchuk** [comment]
Hi Richard, unfortunately there is a problem with this syntax (in the PR)
while this works fine:
```
(def ternary-op
  (m/do*
   (symb "{")
   (condition <- expression)
   (symb "}")
   (yes-exp <- expression)
   (symb "$")
   (no-exp <- expression)
   (m/return (fn [env]
               (if (condition env) (yes-exp env) (no-exp env))))
   )
  )
```
It looks like when the first 'token' is (condition <- expression) then it fails everything. Not sure how to fix it, may be it should be fixed through jasentaa or similar. What do you think?

**Comment by shevchuk** [comment]
@rm-hull the upper syntax worked fine if the test was running separately, but failed with the 'lein test'. So if the condition of the ternary operation will be wrapped with brackets this problem goes away. So latest commit fixes the issue with parsing.

**Comment by rm-hull** [comment]
Hi @shevchuk, was thinking about this - maybe the ternary rule can be promoted over the expression - but I think the brackets is also a good compromise in the meantime.

**Review by rm-hull — APPROVED** [review]

**Comment by rm-hull** [comment]
Deployed to clojars

**Pull request merged**
